name: cicd-pipeline

on: [push]
  #manual trigger
  # push:
  #   - "*/**"
  # pull_request:
  #     branches:
  #       - main

jobs:
  Terraform-actions:
  # env:
    runs-on: ubuntu-latest
    steps:
      - name: Show github variables 
        run : echo "github.ref=${{ github.ref }}; github.event_name=${{github.event_name}}"
      - name: check out the code
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-region: ap-southeast-2
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Initialize Terraform
        run: |
            cd terraform
            terraform init -input=false          
      - name: Plan Terraform
        id: plan
        continue-on-error: true
        run: |
            rm -rf .terraform
            cd terraform
            terraform plan -input=false      
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        id: apply
        run: terraform apply -auto-approve -input=false

        
    